#ifndef _APPLICATION_CONFIG_H
#define _APPLICATION_CONFIG_H_

/*
 * AUTO-GENERATION WARNING:
 *     This header file has been automatically generated from "AppConf.h.cmake".
 *     DO NOT edit this file, as any changes will be automatically discarded.
 */
 
#define APPLICATION_NAME               "Project Name"
#define APPLICATION_CODENAME           "project.name"
#define APPLICATION_COPYRIGHT_YEARS    "2010"

#define APPLICATION_VERSION_MAJOR      1
/* #undef APPLICATION_VERSION_MINOR */
/* #undef APPLICATION_VERSION_PATCH */

#define APPLICATION_VERSION_TYPE       "SNAPSHOT"
#define APPLICATION_VERSION_STRING     "1.0.0-SNAPSHOT"

#define APPLICATION_VENDOR_ID          "com.yourcompany"
#define APPLICATION_VENDOR_NAME        "Your Company"
#define APPLICATION_VENDOR_URL         "yourcompany.com"
#define APPLICATION_ID                 "com.yourcompany"

// Additional configurations

#endif /* _APPLICATION_CONFIG_H_ */
